#!/usr/bin/env bash

set -ex

date

input_file="$1"
contract_name="$2"

compiled_path="$(realpath "compiled/$(basename "$input_file")")"

solc --overwrite --bin-runtime "$input_file" -o "$compiled_path"

cd vandal/
pipenv run bin/analyze.sh "$compiled_path/$contract_name.bin-runtime" datalog/demo_analyses.dl

